# Generated by Django 5.1.3 on 2024-11-15 19:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='A classificação deve ser maior ou igual a 0'), django.core.validators.MaxValueValidator(5, message='A classificação deve ser menor ou igual a 5')], verbose_name='classifiação')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comentário')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='movies.movie')),
            ],
        ),
    ]
