# Generated by Django 5.1.3 on 2024-11-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('UK', 'Reino Unido'), ('JP', 'Japão'), ('BR', 'Brasil'), ('DE', 'Alemanha'), ('FR', 'França'), ('IT', 'Itália'), ('MX', 'México'), ('PT', 'Portugal'), ('ES', 'Espanha')], max_length=50, null=True, verbose_name='nacionalidade')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='biografia')),
            ],
        ),
    ]
