# Generated by Django 5.1.3 on 2024-11-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nome')),
                ('country', models.CharField(choices=[('USA', 'Estados Unidos'), ('UK', 'Reino Unido'), ('JP', 'Japão'), ('BR', 'Brasil'), ('DE', 'Alemanha'), ('FR', 'França'), ('IT', 'Itália'), ('MX', 'México'), ('PT', 'Portugal'), ('ES', 'Espanha')], max_length=3, verbose_name='país')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default=1, max_length=1, verbose_name='sexo'),
            preserve_default=False,
        ),
    ]
